language: node_js
install: npm install git+https://github.com/davidascher/gitbook.git#webmaker-styling
before_script: gitbook install
node_js:
- '0.10'
script: gitbook build
deploy:
  provider: s3
  access_key_id: AKIAIZGNWTZNX5WAIRBQ
  secret_access_key:
    secure: "jsAMhWAH2zm20vZYlaBcqb3WCVw+qASeCW6gQW78pKyLATBdOU4yyOg+LgVJ7tkx7M1t4k2YPljcb4UmJMcN9EIuau+0Pquc1qy3U6VmSDa/KJwrncMxXvYTWqUTCR+iLaL/qZWVtTAkhqeujwE38vQ8qvu0UM3C0v2PmJ04UmY="
  bucket: book-mozillafoundation-org-s3bucket-4hskoi4m627q
  acl: public_read
  skip_cleanup: true
  endpoint: book-mozillafoundation-org-s3bucket-4hskoi4m627q.s3-website-us-east-1.amazonaws.com
  local_dir: _book
