language: node_js
install: npm install git+https://github.com/davidascher/gitbook.git#webmaker-styling
# usually, just:
# install: npm install gitbook
before_script: gitbook install
node_js:
- '0.10'

script: gitbook build
deploy:
  provider: s3
  access_key_id: AKIAJIKEGL5B4WJSCJRQ
  secret_access_key:
    secure: Wqg6+yJud47j78TPqZU+F/SWSgtilzriPw96DU8qtEkaOdIAeZSZTCfb53hxs8GAF8zRXF1h/r+Cn4EflDqhQTkWS64iRvlr5Oqg2KIIeRIUNVukcFBsh1fvAksIu/kl/Mqo6qDouwrSHlmKjDfEuh9+kbjRa3atevpoTFCFJlM=
  bucket: "mofobook"
  acl: public_read
  skip_cleanup: true
  endpoint: "book.webmaker.org.s3-website-us-east-1.amazonaws.com"
  local_dir: "_book"


